In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_audi = pd.read_csv('data/audi.csv')

In [3]:
df_audi.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0    A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1    A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2    A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3    A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4    A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0

`Let's convert the categorical texts into numbers (or you can say in binary)`

`# Earlier I thought I will combine the less frequent models into one, but this will also impact other features, thus due to this I will have to train the models on all columns separately and that will be lengthy...`


Model: Label Encoding (Because it has 15 features)

transmission: OneHotEncoding


fuelType: OneHotEncoding


In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# model_feature = df_audi['model']  # Type Series
model_feature = df_audi[['model']]  # Type DataFrame
# type(model_feature)

label_encoder = LabelEncoder()
encoded_model = label_encoder.fit_transform(model_feature)

c:\Users\knowl\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [5]:
encoded_model

array([0, 5, 0, ..., 2, 9, 9])

In [6]:
# transmission and fuelType

binary_features = df_audi[['transmission', 'fuelType']]

one_hot_encoder = OneHotEncoder()
encoded_binary_features = one_hot_encoder.fit_transform(binary_features)

type(encoded_binary_features), encoded_binary_features.shape

(scipy.sparse._csr.csr_matrix, (10668, 6))

In [7]:
# dummy_df = pd.DataFrame(encoded_binary_features)
encoded_binary_features.todense()

matrix([[0., 1., 0., 0., 0., 1.],
        [1., 0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0., 1.],
        ...,
        [0., 1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0., 1.]])

In [8]:
df_audi[['transmission', 'fuelType']]


transmission fuelType
0           Manual   Petrol
1        Automatic   Diesel
2           Manual   Petrol
3        Automatic   Diesel
4           Manual   Petrol
...            ...      ...
10663       Manual   Petrol
10664       Manual   Petrol
10665       Manual   Petrol
10666    Automatic   Petrol
10667       Manual   Petrol

[10668 rows x 2 columns]

In [9]:
df_audi['transmission'].value_counts(), df_audi['fuelType'].value_counts()

(Manual       4369
 Semi-Auto    3591
 Automatic    2708
 Name: transmission, dtype: int64,
 Diesel    5577
 Petrol    5063
 Hybrid      28
 Name: fuelType, dtype: int64)

In [10]:
one_hot_encoder.categories_

[array(['Automatic', 'Manual', 'Semi-Auto'], dtype=object),
 array(['Diesel', 'Hybrid', 'Petrol'], dtype=object)]

In [11]:
one_hot_features = ['Automatic', 'Manual', 'Semi-Auto', 'Diesel', 'Hybrid', 'Petrol']

In [12]:
# new dataframe create for encoded features and then merge it with old dataframe
# df_audi.merge(encoded_binary_features.todense())


# encoded_df = pd.DataFrame(encoded_binary_features.todense(), columns=one_hot_features)
# encoded_df.head()
# encoded_df['Petrol'] = encoded_model   # It works, that means first I will make a copy of the model feature and then replace the value with encoded_model...
# encoded_df.head()

In [13]:
# df_audi.merge(encoded_df, left_index=True)
# df_audi[one_hot_features] = encoded_binary_features.todense()  # Will do the merging in future when the other columns of dataframe is scaled properly...

In [14]:
df_audi.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0    A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1    A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2    A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3    A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4    A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0

In [15]:
df = df_audi.drop(['model', 'transmission', 'fuelType'], axis=1)
df.head()

year  price  mileage  tax   mpg  engineSize
0  2017  12500    15735  150  55.4         1.4
1  2016  16500    36203   20  64.2         2.0
2  2016  11000    29946   30  55.4         1.4
3  2017  16800    25952  145  67.3         2.0
4  2019  17300     1998  145  49.6         1.0

In [16]:
# what would be the best way to encode year feature???
df['year'].value_counts()
df['year'].unique().__len__(), df_audi['model'].unique().__len__()

(21, 26)

In [17]:
# One Hot Encoding could be the best idea, But if it fails I'll try to do the label encoder, but 21 features is not that big, I should also do the OneHotEncoding to model feature as well...
"""
year_feature, model_one_hot = df[['year']], df_audi[['model']]

encoded_year_feature, encoded_model_feature = one_hot_encoder.fit_transform(year_feature), one_hot_encoder.fit_transform(model_one_hot)
"""

"\nyear_feature, model_one_hot = df[['year']], df_audi[['model']]\n\nencoded_year_feature, encoded_model_feature = one_hot_encoder.fit_transform(year_feature), one_hot_encoder.fit_transform(model_one_hot)\n"

In [18]:
year_model_engine_feature = df_audi[['year', 'model', 'engineSize']]

one_hot_encoder_2 = OneHotEncoder()

year_model_engine_encoded_value = one_hot_encoder_2.fit_transform(year_model_engine_feature)

In [19]:
# one_hot_encoder_2.categories_
one_hot_encoder_2.categories_.__len__()

3

In [20]:
one_hot_encoder_2.categories_[2]

array([0. , 1. , 1.2, 1.4, 1.5, 1.6, 1.8, 1.9, 2. , 2.5, 2.7, 2.9, 3. ,
       3.2, 4. , 4.1, 4.2, 5.2, 6.3])

`Changing df again, now removing the year and engineSize value also. And then I will scale the remaining values so that every data becomes trainable and also plotable...`

1. Handle the thing where you don't want to scale the output value which is price...

In [21]:
year_enginesize_value = df[['year', 'engineSize']]
df = df.drop(['year', 'engineSize'], axis=1)
df.head()

price  mileage  tax   mpg
0  12500    15735  150  55.4
1  16500    36203   20  64.2
2  11000    29946   30  55.4
3  16800    25952  145  67.3
4  17300     1998  145  49.6

In [22]:
# let's even divide the data into Xs and Ys.. And after scaling I will combine everything...

X = df.drop('price', axis=1)
y = df['price'].values

type(X), type(y)

(pandas.core.frame.DataFrame, numpy.ndarray)

In [23]:
# Let's scale

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaled_value = scaler.fit_transform(X)

In [24]:
# type(scaled_value)
scaled_value

array([[-0.3868356 ,  0.35714729,  0.35755001],
       [ 0.48398914, -1.57832278,  1.03713001],
       [ 0.21778089, -1.42944047,  0.35755001],
       ...,
       [-1.03038137,  0.35714729, -0.09035499],
       [-0.68844184,  0.35714729, -0.22163749],
       [-0.55191279,  0.35714729, -0.22163749]])

In [25]:
scaler.feature_names_in_

array(['mileage', 'tax', 'mpg'], dtype=object)

In [26]:
# Create a dataframe so that, you can visualize the data... But wait a second... Now you can't analyze the data, cause it's now too many features.. So yeah be careful from next time, visualize the data before you prepare the data for ML algorithms...

# Prepare the real X and Y value for the train test split and ml models..

X = [encoded_binary_features.todense(), year_model_engine_encoded_value.todense(), scaled_value]

In [27]:
type(encoded_binary_features.todense()), type(year_model_engine_encoded_value.todense()), type(scaled_value)

(numpy.matrix, numpy.matrix, numpy.ndarray)

In [28]:
encoded_binary_features = np.array(encoded_binary_features.todense())
encoded_year_model_engine = np.array(year_model_engine_encoded_value.todense())

In [29]:
# X = np.append(encoded_binary_features, encoded_year_model_engine, scaled_value, axis=1)  # Can't do all together so one by one
X = np.append(encoded_binary_features, encoded_year_model_engine, axis=1)

In [30]:
# X.shape # 10668, 72 -- > Excellant
X = np.append(X, scaled_value, axis=1)

In [31]:
X.shape   # Everything is fine now...

(10668, 75)

In [32]:
# And we had already prepared the y... So yeah time to ML model...

y

array([12500, 16500, 11000, ..., 17199, 19499, 15999], dtype=int64)

In [33]:
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=20)

lin_reg = LinearRegression()

scores = cross_val_score(lin_reg ,X_train, y_train, cv=3)

In [34]:
scores

array([-1.59702132e+21,  9.15012892e-01, -1.09136876e+21])

In [35]:
lin_reg.fit(X_train, y_train)

prediction = lin_reg.predict(X_test)

mean_absolute_error(y_test, prediction)

4251575993744.42

The error is way too much, I guess there is some problem with my data...
1. Do OneHotEncoding is bad for regression problem?
   
GPT: Yes, OneHotEncoding is good for when the features have fewer classes. For big things you should use: LabelEncoder or OrdinalEncoder

In [37]:
df_audi.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0    A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1    A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2    A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3    A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4    A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0

In [38]:
data_for_one_hot_encoding = df_audi[['transmission', 'fuelType']]
one_hot_encoder = OneHotEncoder()
encoded_one_hot_data = one_hot_encoder.fit_transform(data_for_one_hot_encoding)

In [41]:
encoded_one_hot_data.todense().shape  # Nice and easy doyle

(10668, 6)

`for label encoder we need to provide a 1d array, anything more than that won't work, so yeah I've Labelling for all three columns one by one`

In [66]:
# df_audi['tax'].value_counts()


model_data_for_label_encoder = np.ravel(df_audi[['model']])  # Because the Encoder needs data in 1D array
label_encoder_for_model = LabelEncoder()
encoded_model_label_data = label_encoder_for_model.fit_transform(model_data_for_label_encoder)

In [68]:
year_data_for_label_encoder = np.ravel(df_audi[['year']])
label_encoder_for_year = LabelEncoder()
encoded_year_label_data = label_encoder_for_year.fit_transform(year_data_for_label_encoder)

In [69]:
enginesize_data_label_encoder = np.ravel(df_audi[['engineSize']])
label_encoder_for_enginesize = LabelEncoder()
encoded_enginesize_label_data = label_encoder_for_enginesize.fit_transform(enginesize_data_label_encoder)

In [70]:
df = df_audi.copy()

In [81]:
one_hot_encoder.categories_

[array(['Automatic', 'Manual', 'Semi-Auto'], dtype=object),
 array(['Diesel', 'Hybrid', 'Petrol'], dtype=object)]

In [82]:
np.ravel(one_hot_encoder.categories_)

array(['Automatic', 'Manual', 'Semi-Auto', 'Diesel', 'Hybrid', 'Petrol'],
      dtype=object)

In [83]:
encoded_one_hot_data.shape

(10668, 6)

In [101]:
one_hot_features = np.ravel(one_hot_encoder.categories_)
df[one_hot_features] = encoded_one_hot_data.todense()  # Tohar bahinchod, type kara tara aur fir 1 ghante tak baal nocha taaro

In [104]:
df['model'] = encoded_model_label_data
df['year'] = encoded_year_label_data
df['engineSize'] = encoded_enginesize_label_data

In [105]:
df.head()

model  year  price transmission  mileage fuelType  tax   mpg  engineSize  \
0      0    17  12500       Manual    15735   Petrol  150  55.4           3   
1      5    16  16500    Automatic    36203   Diesel   20  64.2           8   
2      0    16  11000       Manual    29946   Petrol   30  55.4           3   
3      3    17  16800    Automatic    25952   Diesel  145  67.3           8   
4      2    19  17300       Manual     1998   Petrol  145  49.6           1   

   Automatic  Manual  Semi-Auto  Diesel  Hybrid  Petrol  
0        0.0     1.0        0.0     0.0     0.0     1.0  
1        1.0     0.0        0.0     1.0     0.0     0.0  
2        0.0     1.0        0.0     0.0     0.0     1.0  
3        1.0     0.0        0.0     1.0     0.0     0.0  
4        0.0     1.0        0.0     0.0     0.0     1.0

In [106]:
dropped_data = df[['transmission', 'fuelType']]
df = df.drop(['transmission', 'fuelType'], axis=1)

df.head()

model  year  price  mileage  tax   mpg  engineSize  Automatic  Manual  \
0      0    17  12500    15735  150  55.4           3        0.0     1.0   
1      5    16  16500    36203   20  64.2           8        1.0     0.0   
2      0    16  11000    29946   30  55.4           3        0.0     1.0   
3      3    17  16800    25952  145  67.3           8        1.0     0.0   
4      2    19  17300     1998  145  49.6           1        0.0     1.0   

   Semi-Auto  Diesel  Hybrid  Petrol  
0        0.0     0.0     0.0     1.0  
1        0.0     1.0     0.0     0.0  
2        0.0     0.0     0.0     1.0  
3        0.0     1.0     0.0     0.0  
4        0.0     0.0     0.0     1.0

In [107]:
# Bhag saala abhi kuchh features ke scale o kare ke baa (features like: mileage, tax, mpg)

data_for_scaling = df[['mileage', 'tax', 'mpg']]
standard_scaler = StandardScaler()
scaled_data = standard_scaler.fit_transform(data_for_scaling)

In [113]:
scaled_data.shape

(10668, 3)

`There are two cases in this scenario:`

1. apply scaling on entire dataset once you are done with encoding (GPT said)
2. and what I'm doing is just applying scaling on required part..
   
so let's see how it goes I'll do 2nd thing first and then 1st thing second. Let's see who is performing better..

!Make sure to make a copy of this current state of dataset so that you can comeback and apply the 1st thing without any problem.

In [109]:
df_copy = df.copy()

In [114]:
df_copy[['mileage', 'tax', 'mpg']] = scaled_data

In [115]:
df_copy.head()

model  year  price   mileage       tax       mpg  engineSize  Automatic  \
0      0    17  12500 -0.386836  0.357147  0.357550           3        0.0   
1      5    16  16500  0.483989 -1.578323  1.037130           8        1.0   
2      0    16  11000  0.217781 -1.429440  0.357550           3        0.0   
3      3    17  16800  0.047853  0.282706  1.276528           8        1.0   
4      2    19  17300 -0.971285  0.282706 -0.090355           1        0.0   

   Manual  Semi-Auto  Diesel  Hybrid  Petrol  
0     1.0        0.0     0.0     0.0     1.0  
1     0.0        0.0     1.0     0.0     0.0  
2     1.0        0.0     0.0     0.0     1.0  
3     0.0        0.0     1.0     0.0     0.0  
4     1.0        0.0     0.0     0.0     1.0

In [117]:
X = df_copy.drop('price', axis=1).values
y = df['price']

In [119]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=20)
lin_reg = LinearRegression()
scores = cross_val_score(lin_reg, X_train, y_train, cv=3)

In [120]:
scores
# Not a bad score: array([0.75735948, 0.74692343, 0.75358099])

array([0.75735948, 0.74692343, 0.75358099])

In [121]:
# let's see the MAE and jump back to the 1st method (scaling the whole dataset and then do the evaluation)
lin_reg.fit(X_train, y_train)
prediction = lin_reg.predict(X_test)
mean_absolute_error(y_test, prediction)

3668.7411990341225

In [123]:
df['price'].min(), df['price'].max()  # Decent score on test set too

(1490, 145000)

#### 1st method: Doing scaling on whole dataset after I've done the encoding of required features...

In [124]:
standard_scaler_for_whole_data = StandardScaler()
scaled_whole_data = standard_scaler_for_whole_data.fit_transform(df.drop('price', axis=1))

In [127]:
y = df['price']
# type(y)

In [129]:
X_train, X_test, y_train, y_test = train_test_split(scaled_whole_data, y, test_size=0.2, random_state=20)
lin_reg_for_whole_data = LinearRegression()
scores = cross_val_score(lin_reg_for_whole_data, X_train, y_train, cv=3)

In [130]:
scores

array([0.75762473, 0.74695531, 0.75364543])

#### Issh almost identical scores, that means scaling other features doesn't make any sense. Encoding had done already a pretty good job. So now I've to focus on other models, to increase the scores... Let's try the Giant one: !Random Forest

In [132]:
from sklearn.ensemble import RandomForestRegressor

random_forest = RandomForestRegressor()
scores = cross_val_score(random_forest, X_train, y_train, cv=3)
scores

array([0.95949563, 0.95048821, 0.95883973])

In [133]:
random_forest.fit(X_train, y_train)
prediction = random_forest.predict(X_test)
mean_absolute_error(y_test, prediction)

1604.8325997375957

#### Random Forest is such a beast model man, I mean look at those scores. It literally killed the data (I mean wow beautiful), training score is also sexy and test score is also sexy...

In [ ]:
# Let's look at other cars in a new file, and will see the exploration too this time...